"""add extra column to google_login_states

Revision ID: 60b03ebbe100
Revises: 6ed6418cca75
Create Date: 2026-06-13 15:25:58.138156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b03ebbe100'
down_revision: Union[str, None] = '6ed6418cca75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_login_states', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_login_states', 'extra')
    # ### end Alembic commands ###
