"""
Integration SDK — CLI scaffolder.

Generates a ready-to-edit ``handler.py`` file for a new integration.

Usage (from Python)::

    from integrations.sdk.cli import generate_integration

    code = generate_integration(
        name="acme",
        display_name="Acme Corp",
        base_url="https://api.acme.com/v1",
        auth_type="bearer",
    )
    # Write to disk:
    import pathlib
    dest = pathlib.Path("integrations/acme/handler.py")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(code)
    print(f"Scaffolded: {dest}")

Usage (from command line)::

    python -m integrations.sdk.cli \\
        --name acme \\
        --display-name "Acme Corp" \\
        --base-url "https://api.acme.com/v1" \\
        --auth-type bearer \\
        [--output integrations/acme/handler.py]

Supported auth types: bearer, apikey_header, apikey_query, basic, oauth2, none
"""
from __future__ import annotations

import keyword
import pathlib
import re
import sys
import textwrap
from typing import Literal

AuthType = Literal["bearer", "apikey_header", "apikey_query", "basic", "oauth2", "none"]

_VALID_AUTH_TYPES = {"bearer", "apikey_header", "apikey_query", "basic", "oauth2", "none"}


def generate_integration(
    name: str,
    display_name: str,
    base_url: str = "",
    auth_type: AuthType = "bearer",
    category: str = "",
    description: str = "",
) -> str:
    """
    Scaffold a new integration ``handler.py`` file.

    Parameters
    ----------
    name:
        Machine-readable integration identifier (e.g. ``"acme"``).
        Must be a valid Python identifier component.
    display_name:
        Human-readable name shown in the UI (e.g. ``"Acme Corp"``).
    base_url:
        The API base URL (e.g. ``"https://api.acme.com/v1"``).
    auth_type:
        One of: ``"bearer"``, ``"apikey_header"``, ``"apikey_query"``,
        ``"basic"``, ``"oauth2"``, ``"none"``.
    category:
        Optional category label for the UI (e.g. ``"CRM"``).
    description:
        Optional short description of the integration.

    Returns
    -------
    str
        Python source code for the new ``handler.py`` file. Write it to
        ``integrations/<name>/handler.py``.
    """
    if not name:
        raise ValueError("name must be non-empty")
    name = name.strip().lower().replace(" ", "_").replace("-", "_")
    if not re.match(r"^[a-z][a-z0-9_]*$", name):
        raise ValueError(
            f"name {name!r} is not a valid integration identifier. "
            "Use lowercase letters, digits, and underscores only."
        )
    if keyword.iskeyword(name):
        raise ValueError(f"name {name!r} is a Python keyword; choose a different name.")

    auth_type = auth_type.strip().lower()  # type: ignore[assignment]
    if auth_type not in _VALID_AUTH_TYPES:
        raise ValueError(
            f"auth_type {auth_type!r} is not supported. "
            f"Choose from: {', '.join(sorted(_VALID_AUTH_TYPES))}"
        )

    class_name = _to_class_name(name)
    description = description or f"Automate {display_name} tasks."
    category = category or ""

    credential_fields_code = _credential_fields_code(auth_type)
    get_headers_code = _get_headers_code(auth_type)
    test_credential_code = _test_credential_code(auth_type)
    example_operation_code = _example_operation_code(name)

    return f'''\
"""
{display_name} integration.

Generated by the Integration SDK scaffolder. Review and complete each
TODO before deploying.

Auth type: {auth_type}
Base URL:  {base_url}
"""
from integrations.sdk.base import BaseIntegration, CredentialField
from integrations.sdk.decorators import operation, trigger


class {class_name}(BaseIntegration):
    name = {name!r}
    display_name = {display_name!r}
    description = {description!r}
    icon = ""  # TODO: set icon URL or icon identifier
    category = {category!r}
    base_url = {base_url!r}

{credential_fields_code}

{get_headers_code}

{test_credential_code}

{example_operation_code}


# ---------------------------------------------------------------------------
# Module-level registration — DO NOT remove this block.
# It registers all @operation / @trigger decorated methods with the
# execution engine when this module is imported.
# ---------------------------------------------------------------------------
_integration = {class_name}()
_integration.register_all()
'''


# ── Auth-specific code snippets ────────────────────────────────────────────────

def _credential_fields_code(auth_type: str) -> str:
    if auth_type == "bearer":
        return textwrap.dedent("""\
            credential_fields = [
                CredentialField(
                    "access_token",
                    "Access Token",
                    type="password",
                    required=True,
                    help_text="Bearer token from the API provider.",
                ),
            ]
        """).rstrip()

    if auth_type == "apikey_header":
        return textwrap.dedent("""\
            credential_fields = [
                CredentialField(
                    "api_key",
                    "API Key",
                    type="password",
                    required=True,
                    help_text="API key sent in the X-API-Key request header.",
                ),
            ]
        """).rstrip()

    if auth_type == "apikey_query":
        return textwrap.dedent("""\
            credential_fields = [
                CredentialField(
                    "api_key",
                    "API Key",
                    type="password",
                    required=True,
                    help_text="API key appended as a query parameter.",
                ),
            ]
        """).rstrip()

    if auth_type == "basic":
        return textwrap.dedent("""\
            credential_fields = [
                CredentialField(
                    "username",
                    "Username",
                    type="text",
                    required=True,
                    help_text="HTTP Basic Auth username.",
                ),
                CredentialField(
                    "password",
                    "Password",
                    type="password",
                    required=True,
                    help_text="HTTP Basic Auth password.",
                ),
            ]
        """).rstrip()

    if auth_type == "oauth2":
        return textwrap.dedent("""\
            credential_fields = [
                CredentialField(
                    "access_token",
                    "OAuth Access Token",
                    type="password",
                    required=True,
                    help_text="OAuth 2.0 access token.",
                ),
                CredentialField(
                    "client_id",
                    "Client ID",
                    type="text",
                    required=False,
                    help_text="OAuth client ID (optional if using a personal access token).",
                ),
                CredentialField(
                    "client_secret",
                    "Client Secret",
                    type="password",
                    required=False,
                    help_text="OAuth client secret.",
                ),
            ]
        """).rstrip()

    # "none" or unknown
    return textwrap.dedent("""\
        credential_fields = [
            # TODO: define credential fields for this integration
            # CredentialField("api_key", "API Key", type="password", required=True),
        ]
    """).rstrip()


def _get_headers_code(auth_type: str) -> str:
    if auth_type == "bearer":
        return textwrap.dedent("""\
            def get_headers(self, credential: dict) -> dict:
                token = credential.get("access_token", "")
                return {"Authorization": f"Bearer {token}"}
        """).rstrip()

    if auth_type == "apikey_header":
        return textwrap.dedent("""\
            def get_headers(self, credential: dict) -> dict:
                # TODO: replace "X-API-Key" with the actual header name for this API
                return {"X-API-Key": credential.get("api_key", "")}
        """).rstrip()

    if auth_type == "apikey_query":
        return textwrap.dedent("""\
            def get_headers(self, credential: dict) -> dict:
                # Auth is passed as a query param; headers are empty.
                # The QueryParamAuth helper in auth.py handles injection per-request.
                return {}

            def build_client(self, credential: dict, **kwargs):
                from integrations.sdk.auth import QueryParamAuth
                from integrations.sdk.http import ResilientHTTPClient
                # TODO: replace "api_key" with the actual query-param name
                auth = QueryParamAuth("api_key", credential.get("api_key", ""))
                return ResilientHTTPClient(
                    provider=self.name,
                    base_url=self.base_url,
                    auth=auth,
                    **kwargs,
                )
        """).rstrip()

    if auth_type == "basic":
        return textwrap.dedent("""\
            def get_headers(self, credential: dict) -> dict:
                import base64
                username = credential.get("username", "")
                password = credential.get("password", "")
                encoded = base64.b64encode(f"{username}:{password}".encode()).decode()
                return {"Authorization": f"Basic {encoded}"}
        """).rstrip()

    if auth_type == "oauth2":
        return textwrap.dedent("""\
            def get_headers(self, credential: dict) -> dict:
                token = credential.get("access_token", "")
                return {"Authorization": f"Bearer {token}"}
        """).rstrip()

    # none
    return textwrap.dedent("""\
        def get_headers(self, credential: dict) -> dict:
            # TODO: add authentication headers
            return {}
    """).rstrip()


def _test_credential_code(auth_type: str) -> str:
    return textwrap.dedent("""\
        async def test_credential(self, credential: dict) -> bool:
            \"\"\"
            Verify this credential actually works.

            TODO: replace GET "/" with a cheap read-only endpoint from
            the API docs (e.g. GET /me, GET /account, GET /ping).
            \"\"\"
            async with self.build_client(credential) as client:
                try:
                    await client.get("/")
                    return True
                except Exception:
                    return False
    """).rstrip()


def _example_operation_code(name: str) -> str:
    return textwrap.dedent(f"""\
        # ── Operations ─────────────────────────────────────────────────────────

        @operation(
            "{name}.list_items",
            label="List Items",
            description="Retrieve a list of items.",
            input_schema={{
                "limit": {{"type": "integer", "required": False, "description": "Max items to return."}},
            }},
            output_schema={{
                "items": {{"type": "array", "description": "List of items."}},
                "total": {{"type": "integer", "description": "Total item count."}},
            }},
        )
        async def list_items(self, config: dict, input_data: dict, credential_id: str, db) -> dict:
            \"\"\"
            TODO: implement this operation.

            1. Load the credential:
               credential = await self._load_credential(credential_id, db)
            2. Build an authenticated client:
               async with self.build_client(credential) as client:
            3. Call the API and return a dict matching output_schema.
            \"\"\"
            limit = config.get("limit") or input_data.get("limit", 100)
            credential = await self._load_credential(credential_id, db)
            async with self.build_client(credential) as client:
                # TODO: replace "/items" with the actual endpoint
                data = await client.get("/items", params={{"limit": limit}})
                items = data if isinstance(data, list) else data.get("items", [])
                return {{"items": items, "total": len(items)}}

        @operation(
            "{name}.get_item",
            label="Get Item",
            description="Retrieve a single item by ID.",
            input_schema={{
                "item_id": {{"type": "string", "required": True, "description": "The item ID."}},
            }},
            output_schema={{
                "id": {{"type": "string"}},
                "name": {{"type": "string"}},
            }},
        )
        async def get_item(self, config: dict, input_data: dict, credential_id: str, db) -> dict:
            \"\"\"TODO: implement this operation.\"\"\"
            item_id = config.get("item_id") or input_data.get("item_id")
            if not item_id:
                raise ValueError("item_id is required")
            credential = await self._load_credential(credential_id, db)
            async with self.build_client(credential) as client:
                # TODO: replace "/items/{{item_id}}" with the actual endpoint
                return await client.get(f"/items/{{item_id}}")

        # TODO: add more operations using @operation or @trigger decorators
    """).rstrip()


# ── Class name helper ──────────────────────────────────────────────────────────

def _to_class_name(name: str) -> str:
    """Convert snake_case integration name to PascalCaseIntegration."""
    parts = name.replace("-", "_").split("_")
    pascal = "".join(p.capitalize() for p in parts if p)
    return pascal + "Integration"


# ── CLI entry point ────────────────────────────────────────────────────────────

def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="Scaffold a new integration handler.py file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python -m integrations.sdk.cli --name acme --display-name "Acme Corp" \\
                  --base-url https://api.acme.com/v1 --auth-type bearer

              python -m integrations.sdk.cli --name stripe --display-name Stripe \\
                  --base-url https://api.stripe.com/v1 --auth-type basic \\
                  --output integrations/stripe_/handler.py
        """),
    )
    parser.add_argument("--name", required=True, help="Machine-readable integration name (snake_case)")
    parser.add_argument("--display-name", required=True, help="Human-readable display name")
    parser.add_argument("--base-url", default="", help="API base URL")
    parser.add_argument(
        "--auth-type",
        default="bearer",
        choices=sorted(_VALID_AUTH_TYPES),
        help="Authentication type (default: bearer)",
    )
    parser.add_argument("--category", default="", help="Integration category (e.g. CRM)")
    parser.add_argument("--description", default="", help="Short description")
    parser.add_argument("--output", default=None, help="Output file path (default: stdout)")

    args = parser.parse_args()

    code = generate_integration(
        name=args.name,
        display_name=args.display_name,
        base_url=args.base_url,
        auth_type=args.auth_type,
        category=args.category,
        description=args.description,
    )

    if args.output:
        dest = pathlib.Path(args.output)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(code)
        print(f"Scaffolded integration written to: {dest}", file=sys.stderr)
    else:
        print(code)


if __name__ == "__main__":
    _main()
