"""GPTZero AI detection integration."""
import httpx
import structlog
from core.execution_engine import register_node

log = structlog.get_logger(__name__)

GPTZERO_BASE = "https://api.gptzero.me/v2"


@register_node("gptzero_detect_ai.detect")
async def gptzero_detect_ai_detect(config: dict, input_data: dict, credential_id: str | None, db) -> dict:
    """Detect whether text was generated by AI using GPTZero.

    config/input_data:
      api_key — GPTZero API key
      text    — text to analyze for AI generation
    """
    merged = {**config, **input_data}
    api_key = merged.get("api_key") or ""
    text = merged.get("text") or ""

    headers = {"x-api-key": api_key, "Content-Type": "application/json"}
    payload = {"document": text}

    async with httpx.AsyncClient(timeout=30) as client:
        r = await client.post(f"{GPTZERO_BASE}/predict/text", headers=headers, json=payload)
        r.raise_for_status()

    result = r.json()
    documents = result.get("documents", [])
    prob = documents[0].get("completely_generated_prob") if documents else None
    log.info("gptzero_detect_ai.detect", completely_generated_prob=prob)
    return {"result": result, "completely_generated_prob": prob}


@register_node("gptzero_detect_ai.detect_file")
async def gptzero_detect_ai_detect_file(config: dict, input_data: dict, credential_id: str | None, db) -> dict:
    """Detect AI-generated content in uploaded files using GPTZero.

    config/input_data:
      api_key   — GPTZero API key
      file_path — local path to the file to analyze
    """
    merged = {**config, **input_data}
    api_key = merged.get("api_key") or ""
    file_path = merged.get("file_path") or ""

    headers = {"x-api-key": api_key}

    with open(file_path, "rb") as f:
        file_bytes = f.read()

    import os
    filename = os.path.basename(file_path)

    async with httpx.AsyncClient(timeout=60) as client:
        r = await client.post(
            f"{GPTZERO_BASE}/predict/files",
            headers=headers,
            files={"files": (filename, file_bytes)},
        )
        r.raise_for_status()

    result = r.json()
    log.info("gptzero_detect_ai.detect_file", file_path=file_path)
    return {"result": result}
